didWalletId: 5
feeWalletId: 1
mintWalletId: 6
mintFromDid: true
isTestnet: true
fundWalletId: 1
royaltyTarget: "txch125c08q7wss65g3ltexs6q2qqznsn2n62m8rzce39ncswpkyqrzks757x6g"
#royaltyTarget: "0x5530f383ce84354447ebc9a1a0280014e1354f4ad9c62c66259e20e0d88018ad"
royaltyPercentage: 1000
minFeePerCost: 0
maxFeePerCost: 20
changeTarget: "0x2fcbeedb166980fb3fdf02e2e4598403905873f9c5bf74ffe4c077637444aba1"    # This need to be a 0x<puzzle_hash> not a xch prefixed addressed
maxRetries: 100
feeIncInterval: 2
retryWaitInterval: 10000
queueMaxWaitSec: 60
queueCheckInterval: 30
jobSize: 50
maxConfirmWait: 240
debugSpendbundle: false
