---
startHeight: 2993180
heightBuffer: 12
isPaused: false
okraDBUri: "http://192.168.122.140:9191"
okraDBUser: "user"
okraDBPass: "pass"
chiaDBUri: "http://192.168.122.201:9191"
chiaDBUser: "user"
chiaDBPass: "pass"
holoPct: 3
goldPct: 20
highLvl: 40
